In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv('../DataSets/Drinks.csv')
df

country  beer_servings  spirit_servings  wine_servings  \
0    Afghanistan              0                0              0   
1        Albania             89              132             54   
2        Algeria             25                0             14   
3        Andorra            245              138            312   
4         Angola            217               57             45   
..           ...            ...              ...            ...   
188    Venezuela            333              100              3   
189      Vietnam            111                2              1   
190        Yemen              6                0              0   
191       Zambia             32               19              4   
192     Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol      continent  
0                             0.0           Asia  
1                             4.9         Europe  
2                             0.7         Africa  
3                            12.4         Europe  
4                             5.9         Africa  
..                            ...            ...  
188                           7.7  South America  
189                           2.0           Asia  
190                           0.1           Asia  
191                           2.5         Africa  
192                           4.7         Africa  

[193 rows x 6 columns]

In [6]:
df.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

In [7]:
df.isnull().sum()

country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
continent                       0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [11]:
df.country=label.fit_transform(df.country)
df.continent=label.fit_transform(df.continent)

In [12]:
df

country  beer_servings  spirit_servings  wine_servings  \
0          0              0                0              0   
1          1             89              132             54   
2          2             25                0             14   
3          3            245              138            312   
4          4            217               57             45   
..       ...            ...              ...            ...   
188      188            333              100              3   
189      189            111                2              1   
190      190              6                0              0   
191      191             32               19              4   
192      192             64               18              4   

     total_litres_of_pure_alcohol  continent  
0                             0.0          1  
1                             4.9          2  
2                             0.7          0  
3                            12.4          2  
4                             5.9          0  
..                            ...        ...  
188                           7.7          5  
189                           2.0          1  
190                           0.1          1  
191                           2.5          0  
192                           4.7          0  

[193 rows x 6 columns]

In [15]:
x=df.drop('total_litres_of_pure_alcohol',axis=1).values
x

array([[  0,   0,   0,   0,   1],
       [  1,  89, 132,  54,   2],
       [  2,  25,   0,  14,   0],
       [  3, 245, 138, 312,   2],
       [  4, 217,  57,  45,   0],
       [  5, 102, 128,  45,   3],
       [  6, 193,  25, 221,   5],
       [  7,  21, 179,  11,   2],
       [  8, 261,  72, 212,   4],
       [  9, 279,  75, 191,   2],
       [ 10,  21,  46,   5,   2],
       [ 11, 122, 176,  51,   3],
       [ 12,  42,  63,   7,   1],
       [ 13,   0,   0,   0,   1],
       [ 14, 143, 173,  36,   3],
       [ 15, 142, 373,  42,   2],
       [ 16, 295,  84, 212,   2],
       [ 17, 263, 114,   8,   3],
       [ 18,  34,   4,  13,   0],
       [ 19,  23,   0,   0,   1],
       [ 20, 167,  41,   8,   5],
       [ 21,  76, 173,   8,   2],
       [ 22, 173,  35,  35,   0],
       [ 23, 245, 145,  16,   5],
       [ 24,  31,   2,   1,   1],
       [ 25, 231, 252,  94,   2],
       [ 26,  25,   7,   7,   0],
       [ 27,  88,   0,   0,   0],
       [ 41,  37,   1,   7,   0],
       [ 28, 1

In [16]:
y=df['total_litres_of_pure_alcohol'].values
y

array([ 0. ,  4.9,  0.7, 12.4,  5.9,  4.9,  8.3,  3.8, 10.4,  9.7,  1.3,
        6.3,  2. ,  0. ,  6.3, 14.4, 10.5,  6.8,  1.1,  0.4,  3.8,  4.6,
        5.4,  7.2,  0.6, 10.3,  4.3,  6.3,  4. ,  4. ,  2.2,  5.8,  8.2,
        1.8,  0.4,  7.6,  5. ,  4.2,  0.1,  1.7,  5.9,  4.4, 10.2,  4.2,
        8.2, 11.8,  0. ,  2.3, 10.4,  1.1,  6.6,  6.2,  4.2,  0.2,  2.2,
        5.8,  0.5,  9.5,  0.7,  2. , 10. , 11.8,  8.9,  2.4,  5.4, 11.3,
        1.8,  8.3, 11.9,  2.2,  0.2,  2.5,  7.1,  5.9,  3. , 11.3,  6.6,
        2.2,  0.1,  0. ,  0.2, 11.4,  2.5,  6.5,  3.4,  7. ,  0.5,  6.8,
        1.8,  1. ,  0. ,  2.4,  6.2, 10.5,  1.9,  2.8,  3.1,  0. , 12.9,
       11.4,  0.8,  1.5,  0.3,  0. ,  0.6,  6.6,  0. ,  0. ,  2.6,  5.5,
        2.3,  0. ,  4.9,  4.9,  0.5,  1.3,  0.1,  6.8,  1. ,  0.2,  9.4,
        9.3,  3.5,  0.1,  9.1,  7. ,  6.7,  0.7,  0. ,  6.9,  7.2,  1.5,
        7.3,  6.1,  4.6, 10.9, 11. ,  0.9,  9.8,  6.3, 10.4, 11.5,  6.8,
        7.7, 10.1,  6.3,  2.6,  0. ,  4.2,  0.1,  0

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.1)

In [18]:
from sklearn.svm import SVR

In [26]:
model=SVR(kernel='linear')

In [27]:
model

SVR(kernel='linear')

In [28]:
model.fit(xtrain,ytrain)

SVR(kernel='linear')

In [29]:
ypred=model.predict(xtest)
ypred

array([ 1.03013079,  0.87903573,  4.95837543,  1.43189816,  2.73417998,
       10.02403907,  6.91999341,  2.61109572,  9.99244897, 12.4892305 ,
       11.66490863,  0.39874907,  6.70036642, 10.3707114 ,  5.07951065,
        1.36317193,  1.22778197,  1.78390708,  1.09338294,  6.33499052])

In [30]:
from sklearn.metrics import r2_score,mean_squared_error
r2=r2_score(ypred,ytest)
r2*100

82.83321387549347